email-validator>=2.2.0
flask>=3.1.1
flask-sqlalchemy>=3.1.1
gradio-client>=1.10.2
gunicorn>=23.0.0
pinecone>=7.0.2
pinecone-client>=6.0.0
psycopg2-binary>=2.9.10
python-dotenv>=1.1.0
requests>=2.32.3
werkzeug>=3.1.3

